name: Node.js CI/CD Deployment

# 1. Tan waxay ka dhigaysaa inuu kiciyo MAR KASTA oo aad code push-gareyso
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # 2. Tan waxay toos ugu soo hagaysaa mashiinkaaga Ubuntu
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Maadaama mashiinkaaga laga yaabo inaanu lahayn 'npm test', kaliya intaan raac
      - run: npm ci

      - name: Restart Application
        run: |
          sudo systemctl restart nginx
          echo "Deployment-ku si guul leh ayuu ugu dhammaaday mishiinkaaga, boss!"